config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end

  resources :users do
    resources :products
  end
  resources :orders
  resources :line_items

  resources :carts
  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

    resources :line_items do
      member do
        post 'decrement'
      end
    end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
	<%= stylesheet_link_tag(
	"application", media: "all",
	"data-turbolinks-track" => true )%>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
	<div id="side">
		<div id="cart">
			<%if !@cart.nil?%>
			<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				<%= render @cart %>
			<% end %>
			<%end%>
		</div>
	
	<ul>
		<li><a href="http://www...."><%=link_to "Home", store_path %></a></li>
		<li><a href="http://www..../faq">Questions</a></li>
		<li><a href="http://www..../news">News</a></li>
		<li><a href="http://www..../contact">Contact</a></li>
		
	</ul>

	<% if session[:user_id] %>
		<ul>
		<li><%= link_to('Orders', orders_path, data: { no_turbolink: true}) %></li>
		<li><%= link_to 'Products', user_products_path(session[:user_id]) %></li>
		<li><%= link_to('Users', users_path, data: { no_turbolink: true}) %></li>
		</ul>
			<%= button_to 'Logout', logout_path, method: :delete %>
	<% end %>
	</div>
	<div id="main">
		<%= yield %>
	</div>
	</div>
</body>
</html>